runtime: python
env: flex
entrypoint: gunicorn -b :$PORT website:app
manual_scaling:
  instances: 1

runtime_config:
    python_version: 3

    # handlers:
    # - url: /.*
    #   script: hello.app
    #
    #
